import "server-only";

import { and, eq, inArray } from "drizzle-orm";
import { Resend } from "resend";

import { db } from "@/lib/db";
import {
  jobReleases,
  jobs,
  notificationDeliveries,
  releaseReadinessNotifications,
  users,
} from "@/lib/db/schema";
import { env } from "@/lib/env";

const resend = env.RESEND_API_KEY ? new Resend(env.RESEND_API_KEY) : null;

export async function deliverReadinessNotifications() {
  const [notifications, recipients] = await Promise.all([
    db
      .select({
        id: releaseReadinessNotifications.id,
        message: releaseReadinessNotifications.message,
        notificationType: releaseReadinessNotifications.notificationType,
        jobReleaseId: releaseReadinessNotifications.jobReleaseId,
        releaseCode: jobReleases.releaseCode,
        jobNumber: jobs.jobNumber,
      })
      .from(releaseReadinessNotifications)
      .innerJoin(jobReleases, eq(releaseReadinessNotifications.jobReleaseId, jobReleases.id))
      .innerJoin(jobs, eq(jobReleases.jobId, jobs.id))
      .where(eq(releaseReadinessNotifications.status, "ACTIVE")),
    db
      .select({
        id: users.id,
        email: users.email,
        name: users.name,
      })
      .from(users)
      .where(
        and(
          eq(users.status, "ACTIVE"),
          inArray(users.activeRole, [
            "platform_admin",
            "ops_lead",
            "department_lead",
          ]),
        ),
      ),
  ]);

  for (const notification of notifications) {
    for (const recipient of recipients) {
      const [delivery] = await db
        .insert(notificationDeliveries)
        .values({
          readinessNotificationId: notification.id,
          channel: "EMAIL",
          recipient: recipient.email,
          status: "PENDING",
          provider: resend ? "resend" : "console",
          metadata: {
            recipientName: recipient.name,
            notificationType: notification.notificationType,
          },
        })
        .onConflictDoNothing()
        .returning({
          id: notificationDeliveries.id,
        });

      if (!delivery) {
        continue;
      }

      try {
        const releaseUrl = `${env.APP_URL}/ops/releases/admin/${notification.jobReleaseId}`;
        if (!resend) {
          console.info(
            `[readiness] ${recipient.email}: ${notification.message} (${releaseUrl})`,
          );
          await db
            .update(notificationDeliveries)
            .set({
              status: "SENT",
              sentAt: new Date(),
            })
            .where(eq(notificationDeliveries.id, delivery.id));
          continue;
        }

        const response = await resend.emails.send({
          from: env.AUTH_FROM_EMAIL,
          to: recipient.email,
          subject: `Release blocked: ${notification.jobNumber} ${notification.releaseCode}`,
          html: `
            <p>${notification.message}</p>
            <p><a href="${releaseUrl}">Open release administration</a></p>
            <p>This notice was generated by Elward Systems Metrics.</p>
          `,
        });

        await db
          .update(notificationDeliveries)
          .set({
            status: "SENT",
            providerMessageId:
              "data" in response && response.data ? response.data.id ?? null : null,
            sentAt: new Date(),
          })
          .where(eq(notificationDeliveries.id, delivery.id));
      } catch (error) {
        await db
          .update(notificationDeliveries)
          .set({
            status: "FAILED",
            errorMessage: error instanceof Error ? error.message : "Unknown delivery error.",
          })
          .where(eq(notificationDeliveries.id, delivery.id));
      }
    }
  }
}
