import "server-only";

import { eq } from "drizzle-orm";

import {
  resolveNotificationRecipients,
  sendEmailNotification,
  shouldSendNotification,
} from "@/features/governance/notifications";
import { db } from "@/lib/db";
import {
  jobReleases,
  jobs,
  notificationDeliveries,
  releaseReadinessNotifications,
} from "@/lib/db/schema";
import { env } from "@/lib/env";

export async function deliverReadinessNotifications() {
  const notifications = await db
    .select({
      id: releaseReadinessNotifications.id,
      message: releaseReadinessNotifications.message,
      notificationType: releaseReadinessNotifications.notificationType,
      jobReleaseId: releaseReadinessNotifications.jobReleaseId,
      releaseCode: jobReleases.releaseCode,
      jobNumber: jobs.jobNumber,
    })
    .from(releaseReadinessNotifications)
    .innerJoin(jobReleases, eq(releaseReadinessNotifications.jobReleaseId, jobReleases.id))
    .innerJoin(jobs, eq(jobReleases.jobId, jobs.id))
    .where(eq(releaseReadinessNotifications.status, "ACTIVE"));

  for (const notification of notifications) {
    const recipients = await resolveNotificationRecipients({
      eventType: notification.notificationType,
      channel: "EMAIL",
    });

    for (const recipient of recipients) {
      const shouldSend = await shouldSendNotification({
        eventType: notification.notificationType,
        channel: "EMAIL",
        recipient: recipient.email,
        readinessNotificationId: notification.id,
        repeatMinutes: recipient.repeatMinutes,
      });

      if (!shouldSend) {
        continue;
      }

      const delivery = await db
        .insert(notificationDeliveries)
        .values({
          eventType: notification.notificationType,
          readinessNotificationId: notification.id,
          channel: "EMAIL",
          recipient: recipient.email,
          status: "PENDING",
          provider: "pending",
          metadata: {
            recipientName: recipient.name,
            escalationOrder: recipient.escalationOrder,
          },
        })
        .returning({
          id: notificationDeliveries.id,
        });

      try {
        const releaseUrl = `${env.APP_URL}/ops/releases/admin/${notification.jobReleaseId}`;
        const sent = await sendEmailNotification({
          recipient: recipient.email,
          subject: `Release blocked: ${notification.jobNumber} ${notification.releaseCode}`,
          html: `
            <p>${notification.message}</p>
            <p><a href="${releaseUrl}">Open release administration</a></p>
            <p>This notice was generated by Elward Systems Metrics.</p>
          `,
        });

        await db
          .update(notificationDeliveries)
          .set({
            status: "SENT",
            provider: sent.provider,
            providerMessageId: sent.providerMessageId,
            sentAt: new Date(),
          })
          .where(eq(notificationDeliveries.id, delivery[0]!.id));
      } catch (error) {
        await db
          .update(notificationDeliveries)
          .set({
            status: "FAILED",
            errorMessage: error instanceof Error ? error.message : "Unknown delivery error.",
          })
          .where(eq(notificationDeliveries.id, delivery[0]!.id));
      }
    }
  }
}
